### ISSUE TITLE
drop tl_formdata

### ISSUE THREAD

**Issue by reluem** [heimrichhannot/contao-fieldpalette#1]
After installing **contao-fieldpalette** via composer on Contao 3.5.6, the database update suggests dropping tl_formdata_ (created by contao-legay/efg).
Dropping the table results in a recreation-drop loop...
Any suggestions on this? 

"contao-legacy/efg": ">=2.2.1.9005,<2.3-dev",
"contao-community-alliance/composer-client": "~0.12",
 "heimrichhannot/contao-fieldpalette": ">=1.0.1.0,<1.1-dev",

**Comment by fatcrobat** [comment]
This seems to be fieldpalette unrelated, can you please disable the module by adding empty .skip file to system/modules/fieldpalette? Clear cache for sure after that and notify us if the drop table still remains?

**Comment by fatcrobat** [comment]
This bug has been reproduced and will be fixed in 1.0.2
